import os
import re
import logging

from lightrag import LightRAG, QueryParam
from lightrag.base import DocStatus

from backend.services.rag.embedding_adapter import embedding_model
from backend.services.rag.groq_adapter import groq_complete

logger = logging.getLogger(__name__)

RAG_SESSIONS_DIR = "./rag_storage/sessions"

# Session IDs are generated by our own frontend (uuid4), but this guards
# against a malformed/malicious value being used to build a filesystem path.
_SAFE_SESSION_ID = re.compile(r"^[a-zA-Z0-9_-]+$")


class RAGService:
    """
    Wraps a single LightRAG instance rooted at its own working_dir, so each
    session's ingested documents and graph/vector stores stay isolated from
    every other session's.
    """

    def __init__(self, working_dir: str):

        os.makedirs(working_dir, exist_ok=True)

        self.rag = LightRAG(
            working_dir=working_dir,

            llm_model_func=groq_complete,
            llm_model_name="llama-3.1-8b-instant",

            embedding_func=embedding_model,

            # Groq's free tier is capped at 6000 tokens/minute. LightRAG's
            # defaults (4 concurrent extraction calls x 3 documents in
            # parallel) can burst well past that in one batch. Serializing
            # here trades some speed for far fewer 429s.
            llm_model_max_async=1,
            max_parallel_insert=1,
        )

        self.initialized = False

    async def initialize(self):

        if not self.initialized:

            await self.rag.initialize_storages()

            self.initialized = True

            logger.info(f"LightRAG initialized at {self.rag.working_dir}")

    async def ingest_document(self, text: str, file_path: str | None = None) -> dict:
        """
        Ingests a document and reports whether LightRAG's own processing
        pipeline (chunking, embedding, entity/relationship extraction)
        actually succeeded, rather than assuming success just because
        ainsert() returned without raising.

        file_path is passed through to LightRAG as citation metadata -
        without it, citations fall back to a generic placeholder title
        instead of the real filename.
        """

        await self.initialize()

        track_id = await self.rag.ainsert(text, file_paths=file_path)

        statuses = await self.rag.aget_docs_by_track_id(track_id)

        failed_errors = [
            doc_status.error_msg or "Unknown error during RAG indexing"
            for doc_status in statuses.values()
            if doc_status.status == DocStatus.FAILED
        ]

        if failed_errors:
            return {"indexed": False, "error": "; ".join(failed_errors)}

        return {"indexed": True, "error": None}

    async def reprocess_failed_documents(self) -> dict:
        """
        Retries indexing for any document in this session that's stuck
        FAILED/PENDING (e.g. entity/relationship extraction previously
        failed from a rate limit or transient error) - those documents
        only ever got plain vector-chunk storage, not the knowledge-graph
        data that makes "mix" mode retrieval useful.

        LightRAG's own apipeline_process_enqueue_documents() already knows
        how to pick up pending/failed/stuck documents and reprocess them;
        this just triggers it directly instead of requiring a throwaway
        re-upload to indirectly kick the same backlog.
        """

        await self.initialize()

        failed_before = await self.rag.get_docs_by_status(DocStatus.FAILED)

        await self.rag.apipeline_process_enqueue_documents()

        failed_after = await self.rag.get_docs_by_status(DocStatus.FAILED)

        return {
            "attempted": len(failed_before),
            "fixed": len(failed_before) - len(failed_after),
            "still_failed": len(failed_after),
        }

    async def ask(self, question: str):

        await self.initialize()

        answer = await self.rag.aquery(

            question,

            param=QueryParam(
                mode="mix"
            )

        )

        return answer


class RAGServiceManager:
    """
    Keeps one RAGService per session_id, each rooted at its own working_dir
    under rag_storage/sessions/. This is what actually provides isolation:
    without it, every session would share one LightRAG instance and one
    knowledge base, and RAG answers could surface any other session's
    uploaded documents.
    """

    def __init__(self):
        self._services: dict[str, RAGService] = {}

    def get(self, session_id: str) -> RAGService:

        if not session_id or not _SAFE_SESSION_ID.match(session_id):
            raise ValueError(f"Invalid session_id: {session_id!r}")

        if session_id not in self._services:
            working_dir = os.path.join(RAG_SESSIONS_DIR, session_id)
            self._services[session_id] = RAGService(working_dir)

        return self._services[session_id]


rag_service_manager = RAGServiceManager()
