import os
import re
import json
import time
import shutil
import logging
from collections import OrderedDict

from lightrag import LightRAG, QueryParam
from lightrag.base import DocStatus

from backend.services.rag.embedding_adapter import embedding_model
from backend.services.rag.groq_adapter import groq_complete

logger = logging.getLogger(__name__)

RAG_SESSIONS_DIR = "./rag_storage/sessions"

# Cap how many LightRAG instances stay live in memory at once. When the cap
# is exceeded, the least-recently-used session is finalized and dropped; its
# data stays on disk and is transparently reloaded if the session returns.
MAX_ACTIVE_SESSIONS = 32

# On-disk session directories not touched within this many days are deleted
# on startup, so RAG storage doesn't grow without bound as sessions accrue.
SESSION_TTL_DAYS = 7

# Session IDs are generated by our own frontend (uuid4), but this guards
# against a malformed/malicious value being used to build a filesystem path.
_SAFE_SESSION_ID = re.compile(r"^[a-zA-Z0-9_-]+$")


class RAGService:
    """
    Wraps a single LightRAG instance rooted at its own working_dir, so each
    session's ingested documents and graph/vector stores stay isolated from
    every other session's.

    working_dir alone is NOT sufficient for isolation: LightRAG's storage
    backends bind to a process-wide shared in-memory dict keyed by
    `workspace` (default: os.getenv("WORKSPACE", "") - the same empty
    string for every instance unless set explicitly). Without passing a
    distinct workspace per session, multiple RAGService instances in this
    one backend process would share that in-memory store and leak data
    across sessions even though each writes to a separate working_dir file.
    """

    def __init__(self, working_dir: str, workspace: str):

        os.makedirs(working_dir, exist_ok=True)

        self.rag = LightRAG(
            working_dir=working_dir,
            workspace=workspace,

            llm_model_func=groq_complete,
            llm_model_name="llama-3.1-8b-instant",

            embedding_func=embedding_model,

            # Groq's free tier is capped at 6000 tokens/minute. LightRAG's
            # defaults (4 concurrent extraction calls x 3 documents in
            # parallel) can burst well past that in one batch. Serializing
            # here trades some speed for far fewer 429s.
            llm_model_max_async=1,
            max_parallel_insert=1,
        )

        self.initialized = False

    async def initialize(self):

        if not self.initialized:

            await self.rag.initialize_storages()

            self.initialized = True

            logger.info(f"LightRAG initialized at {self.rag.working_dir}")

    async def ingest_document(self, text: str, file_path: str | None = None) -> dict:
        """
        Ingests a document and reports whether LightRAG's own processing
        pipeline (chunking, embedding, entity/relationship extraction)
        actually succeeded, rather than assuming success just because
        ainsert() returned without raising.

        file_path is passed through to LightRAG as citation metadata -
        without it, citations fall back to a generic placeholder title
        instead of the real filename.
        """

        await self.initialize()

        track_id = await self.rag.ainsert(text, file_paths=file_path)

        statuses = await self.rag.aget_docs_by_track_id(track_id)

        failed_errors = [
            doc_status.error_msg or "Unknown error during RAG indexing"
            for doc_status in statuses.values()
            if doc_status.status == DocStatus.FAILED
        ]

        if failed_errors:
            return {"indexed": False, "error": "; ".join(failed_errors)}

        return {"indexed": True, "error": None}

    async def reprocess_failed_documents(self) -> dict:
        """
        Retries indexing for any document in this session that's stuck
        FAILED/PENDING (e.g. entity/relationship extraction previously
        failed from a rate limit or transient error) - those documents
        only ever got plain vector-chunk storage, not the knowledge-graph
        data that makes "mix" mode retrieval useful.

        LightRAG's own apipeline_process_enqueue_documents() already knows
        how to pick up pending/failed/stuck documents and reprocess them;
        this just triggers it directly instead of requiring a throwaway
        re-upload to indirectly kick the same backlog.
        """

        await self.initialize()

        failed_before = await self.rag.get_docs_by_status(DocStatus.FAILED)

        await self.rag.apipeline_process_enqueue_documents()

        failed_after = await self.rag.get_docs_by_status(DocStatus.FAILED)

        return {
            "attempted": len(failed_before),
            "fixed": len(failed_before) - len(failed_after),
            "still_failed": len(failed_after),
        }

    async def ask(self, question: str):

        await self.initialize()

        answer = await self.rag.aquery(

            question,

            param=QueryParam(
                mode="mix"
            )

        )

        return answer


class RAGServiceManager:
    """
    Keeps one RAGService per session_id, each rooted at its own working_dir
    under rag_storage/sessions/. This is what actually provides isolation:
    without it, every session would share one LightRAG instance and one
    knowledge base, and RAG answers could surface any other session's
    uploaded documents.

    Instances are held in an LRU cache capped at MAX_ACTIVE_SESSIONS so
    memory doesn't grow unbounded as sessions accumulate; evicted sessions
    are finalized and dropped but their on-disk data is preserved and
    reloaded transparently if the session is used again.
    """

    def __init__(self):
        self._services: "OrderedDict[str, RAGService]" = OrderedDict()

    @staticmethod
    def _validate(session_id: str) -> None:
        if not session_id or not _SAFE_SESSION_ID.match(session_id):
            raise ValueError(f"Invalid session_id: {session_id!r}")

    def session_has_documents(self, session_id: str) -> bool:
        """
        True if this session has at least one ingested document, decided by
        reading the on-disk doc-status store directly. Deliberately does NOT
        create or initialize a LightRAG instance, so merely *querying* an
        empty session no longer leaves a persistent empty directory behind.
        """
        self._validate(session_id)

        session_dir = os.path.join(RAG_SESSIONS_DIR, session_id)
        if not os.path.isdir(session_dir):
            return False

        for root, _, files in os.walk(session_dir):
            if "kv_store_doc_status.json" in files:
                try:
                    with open(os.path.join(root, "kv_store_doc_status.json"),
                              encoding="utf-8") as f:
                        data = json.load(f)
                    if any(isinstance(v, dict) and v.get("status") for v in data.values()):
                        return True
                except Exception:
                    continue
        return False

    async def get(self, session_id: str) -> RAGService:

        self._validate(session_id)

        svc = self._services.get(session_id)
        if svc is not None:
            # Mark as most-recently-used.
            self._services.move_to_end(session_id)
            return svc

        # Evict least-recently-used instances before adding a new one.
        while len(self._services) >= MAX_ACTIVE_SESSIONS:
            old_id, old_svc = self._services.popitem(last=False)
            await self._finalize(old_id, old_svc)

        # LightRAG itself nests a workspace subdirectory under working_dir,
        # so working_dir here is just the shared parent - passing the
        # session_id again would double it up.
        svc = RAGService(RAG_SESSIONS_DIR, workspace=session_id)
        self._services[session_id] = svc
        return svc

    async def _finalize(self, session_id: str, svc: "RAGService") -> None:
        """Release a session's LightRAG storages before dropping it."""
        try:
            if svc.initialized:
                await svc.rag.finalize_storages()
        except Exception as e:
            logger.warning(f"Error finalizing RAG session {session_id}: {e}")
        logger.info(f"Evicted RAG session from memory: {session_id}")

    def sweep_stale_sessions(self, ttl_days: int = SESSION_TTL_DAYS) -> int:
        """
        Delete on-disk session directories whose most recent file is older
        than ttl_days. Sessions currently held in memory are skipped.
        Returns the number of directories removed.
        """
        if not os.path.isdir(RAG_SESSIONS_DIR):
            return 0

        cutoff = time.time() - ttl_days * 86400
        removed = 0

        for name in os.listdir(RAG_SESSIONS_DIR):
            path = os.path.join(RAG_SESSIONS_DIR, name)
            if not os.path.isdir(path) or name in self._services:
                continue
            try:
                if self._last_activity(path) < cutoff:
                    shutil.rmtree(path, ignore_errors=True)
                    removed += 1
            except OSError:
                continue

        if removed:
            logger.info(
                f"Swept {removed} stale RAG session dir(s) older than {ttl_days}d"
            )
        return removed

    @staticmethod
    def _last_activity(path: str) -> float:
        """Most recent mtime among a session dir and its files (LightRAG
        rewrites files in place, so directory mtime alone is unreliable)."""
        latest = os.path.getmtime(path)
        for root, _, files in os.walk(path):
            for f in files:
                try:
                    latest = max(latest, os.path.getmtime(os.path.join(root, f)))
                except OSError:
                    continue
        return latest


rag_service_manager = RAGServiceManager()
