import os
import re
import json
import time
import shutil
import logging
from collections import OrderedDict

from lightrag import LightRAG, QueryParam
from lightrag.base import DocStatus

from backend.services.rag.embedding_adapter import embedding_model
from backend.services.rag.groq_adapter import groq_complete

logger = logging.getLogger(__name__)

RAG_SESSIONS_DIR = "./rag_storage/sessions"

# Cap how many LightRAG instances stay live in memory at once. When the cap
# is exceeded, the least-recently-used session is finalized and dropped; its
# data stays on disk and is transparently reloaded if the session returns.
MAX_ACTIVE_SESSIONS = 32

# On-disk session directories not touched within this many days are deleted
# on startup, so RAG storage doesn't grow without bound as sessions accrue.
SESSION_TTL_DAYS = 7

# Session IDs are generated by our own frontend (uuid4), but this guards
# against a malformed/malicious value being used to build a filesystem path.
_SAFE_SESSION_ID = re.compile(r"^[a-zA-Z0-9_-]+$")

# Structure-aware chunking: a split character is inserted before each
# structural marker the file processor emits, so LightRAG chunks on document
# structure (page / table / sheet / text-box boundaries) instead of blindly by
# token count - keeping a financial table intact in one chunk rather than split
# across two. The marker stays at the segment start, so page/table provenance
# rides along into the chunk (and thus into what the LLM cites).
_SEGMENT_CHAR = "\f"
_SEGMENT_MARKER_RE = re.compile(
    r"(?=(?:--- Page \d+ ---|\[Table|\[Sheet:|\[Nested table\]|\[Text box\]))"
)


class RAGService:
    """
    Wraps a single LightRAG instance rooted at its own working_dir, so each
    session's ingested documents and graph/vector stores stay isolated from
    every other session's.

    working_dir alone is NOT sufficient for isolation: LightRAG's storage
    backends bind to a process-wide shared in-memory dict keyed by
    `workspace` (default: os.getenv("WORKSPACE", "") - the same empty
    string for every instance unless set explicitly). Without passing a
    distinct workspace per session, multiple RAGService instances in this
    one backend process would share that in-memory store and leak data
    across sessions even though each writes to a separate working_dir file.
    """

    def __init__(self, working_dir: str, workspace: str,
                 llm_model_func=groq_complete,
                 llm_model_name: str = "openai/gpt-oss-20b"):

        os.makedirs(working_dir, exist_ok=True)

        self.rag = LightRAG(
            working_dir=working_dir,
            workspace=workspace,

            # Defaults preserve the production behaviour (Groq). They can be
            # overridden to run the whole RAG pipeline on another provider - used
            # by the per-model evaluation harness.
            llm_model_func=llm_model_func,
            llm_model_name=llm_model_name,

            embedding_func=embedding_model,

            # Groq's free tier is capped at 6000 tokens/minute. LightRAG's
            # defaults (4 concurrent extraction calls x 3 documents in
            # parallel) can burst well past that in one batch. Serializing
            # here trades some speed for far fewer 429s.
            llm_model_max_async=1,
            max_parallel_insert=1,
        )

        self.initialized = False

    async def initialize(self):

        if not self.initialized:

            await self.rag.initialize_storages()

            self.initialized = True

            logger.info(f"LightRAG initialized at {self.rag.working_dir}")

    async def _delete_docs_by_filename(self, file_path: str) -> int:
        """
        Delete any already-ingested document(s) with this filename. Called
        before a re-upload so an updated document REPLACES the old version -
        otherwise LightRAG rejects the re-upload as a duplicate and keeps
        serving the stale content. Returns how many docs were removed.
        """
        doc_ids = set()
        for status in DocStatus:
            try:
                docs = await self.rag.get_docs_by_status(status)
            except Exception:
                continue
            for doc_id, st in docs.items():
                if getattr(st, "file_path", None) == file_path:
                    doc_ids.add(doc_id)

        removed = 0
        for doc_id in doc_ids:
            try:
                await self.rag.adelete_by_doc_id(doc_id)
                removed += 1
            except Exception as e:
                logger.warning(f"Failed to delete old doc {doc_id} for {file_path}: {e}")

        if removed:
            logger.info(f"Replaced {removed} existing doc(s) for filename '{file_path}'")
        return removed

    async def ingest_document(self, text: str, file_path: str | None = None) -> dict:
        """
        Ingests a document and reports whether LightRAG's own processing
        pipeline (chunking, embedding, entity/relationship extraction)
        actually succeeded, rather than assuming success just because
        ainsert() returned without raising.

        file_path is passed through to LightRAG as citation metadata (and
        used to replace an earlier version of the same file - see below).

        Returns {"indexed": bool, "error": str|None, "replaced": int,
                 "duplicate": bool}.
        """

        await self.initialize()

        # Re-uploading a file with the same name should REPLACE the previous
        # version (e.g. a restated financial report), not be silently dropped
        # as a duplicate. Remove any existing doc for this filename first.
        replaced = 0
        if file_path:
            replaced = await self._delete_docs_by_filename(file_path)

        # Chunk on document structure (see _SEGMENT_MARKER_RE) rather than
        # blindly by token count. split_by_character_only=False means a segment
        # larger than the token cap is still further split, so huge pages don't
        # become one giant chunk. Fall back to a plain insert if this LightRAG
        # build doesn't accept the split arguments.
        segmented = _SEGMENT_MARKER_RE.sub(_SEGMENT_CHAR, text)
        try:
            track_id = await self.rag.ainsert(
                segmented,
                split_by_character=_SEGMENT_CHAR,
                split_by_character_only=False,
                file_paths=file_path,
            )
        except TypeError:
            logger.warning(
                "LightRAG.ainsert lacks split_by_character; using plain insert "
                "(structure-aware chunking inactive on this build)."
            )
            track_id = await self.rag.ainsert(text, file_paths=file_path)

        statuses = await self.rag.aget_docs_by_track_id(track_id)

        failed_errors = []
        duplicate = False
        for doc_status in statuses.values():
            if doc_status.status != DocStatus.FAILED:
                continue
            error_msg = doc_status.error_msg or ""
            metadata = getattr(doc_status, "metadata", {}) or {}
            # A content-hash duplicate (identical text already present, e.g.
            # under a different filename) isn't a real failure - the content
            # is already searchable.
            if metadata.get("is_duplicate") or "already exists" in error_msg.lower():
                duplicate = True
            else:
                failed_errors.append(error_msg or "Unknown error during RAG indexing")

        if failed_errors:
            return {"indexed": False, "error": "; ".join(failed_errors),
                    "replaced": replaced, "duplicate": False}

        return {"indexed": True, "error": None,
                "replaced": replaced, "duplicate": duplicate}

    async def reprocess_failed_documents(self) -> dict:
        """
        Retries indexing for any document in this session that's stuck
        FAILED/PENDING (e.g. entity/relationship extraction previously
        failed from a rate limit or transient error) - those documents
        only ever got plain vector-chunk storage, not the knowledge-graph
        data that makes "mix" mode retrieval useful.

        LightRAG's own apipeline_process_enqueue_documents() already knows
        how to pick up pending/failed/stuck documents and reprocess them;
        this just triggers it directly instead of requiring a throwaway
        re-upload to indirectly kick the same backlog.
        """

        await self.initialize()

        failed_before = await self.rag.get_docs_by_status(DocStatus.FAILED)

        await self.rag.apipeline_process_enqueue_documents()

        failed_after = await self.rag.get_docs_by_status(DocStatus.FAILED)

        return {
            "attempted": len(failed_before),
            "fixed": len(failed_before) - len(failed_after),
            "still_failed": len(failed_after),
        }

    async def ask(self, question: str, persona: str | None = None):

        await self.initialize()

        # Persona-aware answering: when a persona is given, its style guide (and a
        # HARD numeric guardrail) are injected into LightRAG's own rag_response
        # template via QueryParam.user_prompt (the template's "Additional
        # Instructions" slot). This keeps LightRAG's full mix-mode retrieval and
        # its grounding/citation behaviour intact, and only changes HOW the
        # grounded answer is worded for the reader - never the facts or figures.
        user_prompt = self._build_persona_user_prompt(persona) if persona else None

        # No rerank model is configured in this deployment, so disable
        # reranking explicitly - otherwise LightRAG logs a "Rerank is enabled
        # but no rerank model is configured" warning on every query. Retrieval
        # still uses graph + vector (mix) recall. Fall back gracefully if an
        # older LightRAG build doesn't accept these parameters.
        try:
            param = QueryParam(mode="mix", enable_rerank=False)
            if persona:
                param.user_prompt = user_prompt
                # Length/depth lever: bias the answer's shape to the reader.
                param.response_type = self._persona_response_type(persona)
            answer = await self.rag.aquery(question, param=param)
        except TypeError:
            answer = await self.rag.aquery(question, param=QueryParam(mode="mix"))

        return answer

    # Per-persona answer shape, fed to LightRAG's response_type slot ("The
    # response should be presented in {response_type}"). Keyed by the persona
    # name with any " Persona" suffix stripped and lower-cased.
    _RESPONSE_TYPES = {
        "student": "a short, simple explanation in plain everyday language for someone "
                   "with no finance background, using one relatable analogy and as few words as possible",
        "engineering student": "a concise, logically structured, precise explanation",
        "mba student": "a thorough, analytical explanation using appropriate financial "
                       "terminology and business framing",
        "teacher": "a clear, well-structured explanation that defines each term as it is used",
        "clerk": "a clear, practical explanation in plain language focused on what it means day to day",
        "homemaker": "a simple, friendly explanation in everyday language with a household "
                     "analogy and no jargon",
        "retiree": "a calm, plain-language explanation with no jargon, focused on what it means",
        "senior citizen": "a brief, very plain, reassuring explanation with no jargon at all",
        "general user": "a clear, concise explanation in plain language",
    }
    _DEFAULT_RESPONSE_TYPE = "a clear explanation pitched to the reader described"

    @classmethod
    def _persona_response_type(cls, persona: str) -> str:
        key = (persona or "").lower().replace(" persona", "").strip()
        return cls._RESPONSE_TYPES.get(key, cls._DEFAULT_RESPONSE_TYPE)

    @staticmethod
    def _build_persona_user_prompt(persona: str) -> str:
        """
        Build the "Additional Instructions" block injected into LightRAG's
        rag_response template: a non-negotiable numeric guardrail first, then a
        forceful instruction to genuinely tailor the explanation to the reader.
        The guardrail is declared to override the styling, so adapting the answer
        to the reader can never change a figure.
        """
        from utils.persona_manager import get_persona_prompt
        style = get_persona_prompt(persona)
        return (
            "HARD RULE (overrides every style instruction below, never violate): "
            "Reproduce every number, figure, percentage, ratio, date, and currency "
            "amount EXACTLY as it appears in the Context. Do NOT change, round, "
            "re-scale, reformat, approximate, translate, or invent any figure, and do "
            "not alter the citations. If a figure is not in the Context, do not state "
            "one. Adjusting the answer for the reader must never change the data.\n\n"
            "REWRITE FOR THIS READER (important, not optional): genuinely adapt the "
            "explanation's vocabulary, sentence complexity, depth, tone, and length to "
            "the reader described below. Two different readers must receive noticeably "
            "different explanations of the SAME facts - a beginner should get short, "
            "jargon-free, analogy-led wording; an expert should get concise, technical "
            "wording. Keep all facts, figures, and citations identical.\n"
            f"READER PROFILE:\n{style}"
        )

    async def get_context(self, question: str) -> str:
        """
        Return the retrieved document context for a question WITHOUT letting
        LightRAG synthesize an answer (only_need_context=True). Used by the
        web+document blend so the retrieved chunks can be combined with web
        results into a single cited answer. Returns "" if unavailable.
        """
        await self.initialize()
        try:
            ctx = await self.rag.aquery(
                question,
                param=QueryParam(
                    mode="mix", only_need_context=True, enable_rerank=False
                ),
            )
        except TypeError:
            # Older LightRAG without only_need_context: fall back to the answer.
            ctx = await self.rag.aquery(
                question, param=QueryParam(mode="mix", enable_rerank=False)
            )
        return ctx or ""


class RAGServiceManager:
    """
    Keeps one RAGService per session_id, each rooted at its own working_dir
    under rag_storage/sessions/. This is what actually provides isolation:
    without it, every session would share one LightRAG instance and one
    knowledge base, and RAG answers could surface any other session's
    uploaded documents.

    Instances are held in an LRU cache capped at MAX_ACTIVE_SESSIONS so
    memory doesn't grow unbounded as sessions accumulate; evicted sessions
    are finalized and dropped but their on-disk data is preserved and
    reloaded transparently if the session is used again.
    """

    def __init__(self):
        self._services: "OrderedDict[str, RAGService]" = OrderedDict()

    @staticmethod
    def _validate(session_id: str) -> None:
        if not session_id or not _SAFE_SESSION_ID.match(session_id):
            raise ValueError(f"Invalid session_id: {session_id!r}")

    def session_has_documents(self, session_id: str) -> bool:
        """
        True if this session has at least one ingested document, decided by
        reading the on-disk doc-status store directly. Deliberately does NOT
        create or initialize a LightRAG instance, so merely *querying* an
        empty session no longer leaves a persistent empty directory behind.
        """
        self._validate(session_id)

        session_dir = os.path.join(RAG_SESSIONS_DIR, session_id)
        if not os.path.isdir(session_dir):
            return False

        for root, _, files in os.walk(session_dir):
            if "kv_store_doc_status.json" in files:
                try:
                    with open(os.path.join(root, "kv_store_doc_status.json"),
                              encoding="utf-8") as f:
                        data = json.load(f)
                    if any(isinstance(v, dict) and v.get("status") for v in data.values()):
                        return True
                except Exception:
                    continue
        return False

    async def get(self, session_id: str) -> RAGService:

        self._validate(session_id)

        svc = self._services.get(session_id)
        if svc is not None:
            # Mark as most-recently-used.
            self._services.move_to_end(session_id)
            return svc

        # Evict least-recently-used instances before adding a new one.
        while len(self._services) >= MAX_ACTIVE_SESSIONS:
            old_id, old_svc = self._services.popitem(last=False)
            await self._finalize(old_id, old_svc)

        # LightRAG itself nests a workspace subdirectory under working_dir,
        # so working_dir here is just the shared parent - passing the
        # session_id again would double it up.
        svc = RAGService(RAG_SESSIONS_DIR, workspace=session_id)
        self._services[session_id] = svc
        return svc

    async def _finalize(self, session_id: str, svc: "RAGService") -> None:
        """Release a session's LightRAG storages before dropping it."""
        try:
            if svc.initialized:
                await svc.rag.finalize_storages()
        except Exception as e:
            logger.warning(f"Error finalizing RAG session {session_id}: {e}")
        logger.info(f"Evicted RAG session from memory: {session_id}")

    def sweep_stale_sessions(self, ttl_days: int = SESSION_TTL_DAYS) -> int:
        """
        Delete on-disk session directories whose most recent file is older
        than ttl_days. Sessions currently held in memory are skipped.
        Returns the number of directories removed.
        """
        if not os.path.isdir(RAG_SESSIONS_DIR):
            return 0

        cutoff = time.time() - ttl_days * 86400
        removed = 0

        for name in os.listdir(RAG_SESSIONS_DIR):
            path = os.path.join(RAG_SESSIONS_DIR, name)
            if not os.path.isdir(path) or name in self._services:
                continue
            try:
                if self._last_activity(path) < cutoff:
                    shutil.rmtree(path, ignore_errors=True)
                    removed += 1
            except OSError:
                continue

        if removed:
            logger.info(
                f"Swept {removed} stale RAG session dir(s) older than {ttl_days}d"
            )
        return removed

    @staticmethod
    def _last_activity(path: str) -> float:
        """Most recent mtime among a session dir and its files (LightRAG
        rewrites files in place, so directory mtime alone is unreliable)."""
        latest = os.path.getmtime(path)
        for root, _, files in os.walk(path):
            for f in files:
                try:
                    latest = max(latest, os.path.getmtime(os.path.join(root, f)))
                except OSError:
                    continue
        return latest


rag_service_manager = RAGServiceManager()
